"""
avalia+ — Dados de demonstração de Aracaju, SE
Todos os estabelecimentos localizados no Centro de Aracaju.
"""

# ── USUÁRIO FIXO (sem autenticação) ──────────────────────────────────────────
USUARIO_ATUAL = {
    "id": 1,
    "nome": "Visitante",
    "tipo": "consumidor",
}

# ── COMÉRCIOS ─────────────────────────────────────────────────────────────────
COMERCIOS = [
    {
        "id": 1,
        "nome": "Churrascaria Xingó",
        "categoria": "Restaurante",
        "bairro": "Centro",
        "endereco": "Rua Laranjeiras, 120, Centro, Aracaju-SE",
        "horario": "11h – 23h",
        "emoji": "🍖",
        "nota_media": 4.9,
        "total_avaliacoes": 248,
        "plano": "premium",
        "descricao": "A melhor churrascaria do Centro de Aracaju, com tradição de mais de 10 anos. Picanha, maminha e costela preparadas na brasa por especialistas.",
        "tags": ["Familiar", "Churrasqueira", "Grupos"],
        "dist_notas": {5: 196, 4: 38, 3: 10, 2: 3, 1: 1},
    },
    {
        "id": 2,
        "nome": "Farmácia Saúde Viva",
        "categoria": "Farmácia",
        "bairro": "Centro",
        "endereco": "Av. Ivo do Prado, 310, Centro, Aracaju-SE",
        "horario": "07h – 22h",
        "emoji": "💊",
        "nota_media": 4.7,
        "total_avaliacoes": 112,
        "plano": "premium",
        "descricao": "Farmácia completa com manipulação, entrega em domicílio e farmacêutico disponível para orientações.",
        "tags": ["Entrega", "Manipulação", "Plantão"],
        "dist_notas": {5: 80, 4: 22, 3: 7, 2: 2, 1: 1},
    },
    {
        "id": 3,
        "nome": "Mercado Bom Preço",
        "categoria": "Mercado",
        "bairro": "Centro",
        "endereco": "Rua João Pessoa, 88, Centro, Aracaju-SE",
        "horario": "07h – 21h",
        "emoji": "🛒",
        "nota_media": 4.5,
        "total_avaliacoes": 89,
        "plano": "freemium",
        "descricao": "Supermercado de bairro com hortifrúti fresquinho e os melhores preços do Centro de Aracaju.",
        "tags": ["Hortifrúti", "Açougue", "Padaria"],
        "dist_notas": {5: 50, 4: 28, 3: 9, 2: 2, 1: 0},
    },
    {
        "id": 4,
        "nome": "Café Cotinguiba",
        "categoria": "Café",
        "bairro": "Centro",
        "endereco": "Rua de Estância, 540, Centro, Aracaju-SE",
        "horario": "07h – 20h",
        "emoji": "☕",
        "nota_media": 4.8,
        "total_avaliacoes": 203,
        "plano": "premium",
        "descricao": "Café artesanal no coração do Centro histórico. Brunchs especiais aos fins de semana e tortas artesanais.",
        "tags": ["Brunch", "Histórico", "Artesanal"],
        "dist_notas": {5: 160, 4: 32, 3: 8, 2: 2, 1: 1},
    },
    {
        "id": 5,
        "nome": "Boutique Centro Moda",
        "categoria": "Moda",
        "bairro": "Centro",
        "endereco": "Rua Itabaianinha, 230, Centro, Aracaju-SE",
        "horario": "09h – 19h",
        "emoji": "👗",
        "nota_media": 4.3,
        "total_avaliacoes": 56,
        "plano": "freemium",
        "descricao": "Moda feminina com peças exclusivas de estilistas sergipanos e atendimento personalizado.",
        "tags": ["Exclusivo", "Local", "Feminino"],
        "dist_notas": {5: 28, 4: 18, 3: 7, 2: 2, 1: 1},
    },
    {
        "id": 6,
        "nome": "Clínica Médica São Lucas",
        "categoria": "Saúde",
        "bairro": "Centro",
        "endereco": "Av. Hermes Fontes, 412, Centro, Aracaju-SE",
        "horario": "08h – 18h",
        "emoji": "🏥",
        "nota_media": 4.6,
        "total_avaliacoes": 134,
        "plano": "premium",
        "descricao": "Clínica multidisciplinar com cardiologia, ortopedia, dermatologia e fisioterapia no Centro de Aracaju.",
        "tags": ["Convênio", "Especialistas", "Agendamento Online"],
        "dist_notas": {5: 90, 4: 32, 3: 9, 2: 2, 1: 1},
    },
    {
        "id": 7,
        "nome": "Pizzaria do Mercado",
        "categoria": "Restaurante",
        "bairro": "Centro",
        "endereco": "Rua Capela, 34, Centro, Aracaju-SE",
        "horario": "18h – 00h",
        "emoji": "🍕",
        "nota_media": 4.4,
        "total_avaliacoes": 178,
        "plano": "freemium",
        "descricao": "Pizza artesanal com massa fina e ingredientes frescos próximo ao Mercado Municipal. Entrega rápida.",
        "tags": ["Delivery", "Artesanal", "Massa Fina"],
        "dist_notas": {5: 100, 4: 55, 3: 18, 2: 4, 1: 1},
    },
    {
        "id": 8,
        "nome": "Açaí da Praça",
        "categoria": "Café",
        "bairro": "Centro",
        "endereco": "Praça Olímpio Campos, 10, Centro, Aracaju-SE",
        "horario": "10h – 22h",
        "emoji": "🫐",
        "nota_media": 4.9,
        "total_avaliacoes": 321,
        "plano": "premium",
        "descricao": "O açaí mais famoso do Centro de Aracaju, na icônica Praça Olímpio Campos. Mais de 30 coberturas.",
        "tags": ["Famoso", "Praça", "Açaí"],
        "dist_notas": {5: 270, 4: 40, 3: 8, 2: 2, 1: 1},
    },
    {
        "id": 9,
        "nome": "Drogaria Central",
        "categoria": "Farmácia",
        "bairro": "Centro",
        "endereco": "Rua Sergipe, 190, Centro, Aracaju-SE",
        "horario": "07h – 22h",
        "emoji": "💉",
        "nota_media": 4.2,
        "total_avaliacoes": 67,
        "plano": "freemium",
        "descricao": "Drogaria com os melhores preços em medicamentos genéricos e de referência no Centro.",
        "tags": ["Preço Baixo", "Genéricos", "Centro"],
        "dist_notas": {5: 35, 4: 20, 3: 8, 2: 3, 1: 1},
    },
    {
        "id": 10,
        "nome": "Restaurante Caju & Cia",
        "categoria": "Restaurante",
        "bairro": "Centro",
        "endereco": "Rua Divina Pastora, 78, Centro, Aracaju-SE",
        "horario": "11h – 15h",
        "emoji": "🥘",
        "nota_media": 4.6,
        "total_avaliacoes": 145,
        "plano": "premium",
        "descricao": "Culinária sergipana autêntica: carne de sol, arroz de leite, feijão temperado e muito mais no almoço.",
        "tags": ["Sergipano", "Almoço", "Tradicional"],
        "dist_notas": {5: 95, 4: 38, 3: 9, 2: 2, 1: 1},
    },
    {
        "id": 11,
        "nome": "Ótica Horizonte Centro",
        "categoria": "Moda",
        "bairro": "Centro",
        "endereco": "Rua Itabaianinha, 105, Centro, Aracaju-SE",
        "horario": "09h – 18h",
        "emoji": "👓",
        "nota_media": 4.5,
        "total_avaliacoes": 78,
        "plano": "freemium",
        "descricao": "Óculos de grau e solares das melhores marcas com preços acessíveis no coração do Centro.",
        "tags": ["Grau", "Solar", "Marcas"],
        "dist_notas": {5: 45, 4: 22, 3: 8, 2: 2, 1: 1},
    },
    {
        "id": 12,
        "nome": "Mercadinho São Francisco",
        "categoria": "Mercado",
        "bairro": "Centro",
        "endereco": "Rua Santo Amaro, 55, Centro, Aracaju-SE",
        "horario": "06h – 20h",
        "emoji": "🧺",
        "nota_media": 4.1,
        "total_avaliacoes": 42,
        "plano": "freemium",
        "descricao": "Mercadinho tradicional do Centro com hortifrúti fresquinho entregue diretamente da feira.",
        "tags": ["Feira", "Fresquinho", "Tradicional"],
        "dist_notas": {5: 20, 4: 14, 3: 5, 2: 2, 1: 1},
    },
]

# ── AVALIAÇÕES ────────────────────────────────────────────────────────────────
AVALIACOES = {
    1: [
        {"usuario": "Maria S.", "emoji": "👩", "nota": 5, "comentario": "Melhor churrasco do Centro! A picanha estava no ponto perfeito e o atendimento foi impecável. Voltarei com certeza!", "data": "2 dias atrás", "sentimento": "positivo"},
        {"usuario": "João P.", "emoji": "👨", "nota": 4, "comentario": "Muito bom! Ambiente agradável e carne de qualidade. Só o tempo de espera no sábado foi um pouco longo.", "data": "5 dias atrás", "sentimento": "neutro"},
        {"usuario": "Ana C.", "emoji": "🧑", "nota": 5, "comentario": "Simplesmente perfeito! O melhor lugar para almoçar no Centro. Já indiquei para toda a família.", "data": "1 semana atrás", "sentimento": "positivo"},
        {"usuario": "Carlos M.", "emoji": "👴", "nota": 3, "comentario": "Produto bom mas esperei 40 minutos para ser atendido. Precisa melhorar o atendimento nos horários de pico.", "data": "2 semanas atrás", "sentimento": "negativo"},
        {"usuario": "Fernanda O.", "emoji": "👩‍🦱", "nota": 5, "comentario": "Ambiente aconchegante, carne deliciosa e preço justo. Perfeito para reunir a família!", "data": "3 semanas atrás", "sentimento": "positivo"},
    ],
    2: [
        {"usuario": "Paulo R.", "emoji": "👨‍⚕️", "nota": 5, "comentario": "Farmacêutico muito atencioso, me orientou sobre a medicação e tirou todas as dúvidas. Excelente serviço!", "data": "1 dia atrás", "sentimento": "positivo"},
        {"usuario": "Lúcia F.", "emoji": "👩‍🦳", "nota": 4, "comentario": "Ótima farmácia, preço bom e entrega rápida. A manipulação é de qualidade.", "data": "4 dias atrás", "sentimento": "positivo"},
        {"usuario": "Ricardo N.", "emoji": "🧔", "nota": 5, "comentario": "Sempre encontro o que preciso aqui. Equipe muito bem treinada e prestativa.", "data": "1 semana atrás", "sentimento": "positivo"},
        {"usuario": "Sandra K.", "emoji": "👩", "nota": 3, "comentario": "Às vezes falta estoque de remédios comuns. Precisam melhorar o abastecimento.", "data": "2 semanas atrás", "sentimento": "neutro"},
    ],
    3: [
        {"usuario": "Marcos L.", "emoji": "🧑‍🍳", "nota": 5, "comentario": "Hortifrúti sempre fresquinho e preços imbatíveis. O melhor mercado do Centro!", "data": "3 dias atrás", "sentimento": "positivo"},
        {"usuario": "Joana B.", "emoji": "👩‍🦰", "nota": 4, "comentario": "Bom para as compras do dia a dia. Açougue de qualidade e atendimento simpático.", "data": "1 semana atrás", "sentimento": "positivo"},
        {"usuario": "Alberto S.", "emoji": "👴", "nota": 4, "comentario": "Preços muito competitivos. As filas nos horários de pico são o único problema.", "data": "2 semanas atrás", "sentimento": "neutro"},
    ],
    4: [
        {"usuario": "Camila T.", "emoji": "👩‍🎨", "nota": 5, "comentario": "O melhor café do Centro! O flat white é incrível e os croissants são fresquíssimos. Atmosfera linda!", "data": "1 dia atrás", "sentimento": "positivo"},
        {"usuario": "Bruno A.", "emoji": "👨‍💻", "nota": 5, "comentario": "Trabalho aqui toda semana. Wi-Fi ótimo, ambiente tranquilo e o café é realmente especial.", "data": "3 dias atrás", "sentimento": "positivo"},
        {"usuario": "Tatiana M.", "emoji": "👩", "nota": 4, "comentario": "Brunch maravilhoso! A torta de limão é de comer rezando. Só achei o preço um pouco salgado.", "data": "1 semana atrás", "sentimento": "positivo"},
        {"usuario": "Gustavo P.", "emoji": "🧔", "nota": 5, "comentario": "Descobri esse café há pouco e já é meu favorito. Qualidade excepcional!", "data": "2 semanas atrás", "sentimento": "positivo"},
    ],
    5: [
        {"usuario": "Patrícia L.", "emoji": "👩‍🦱", "nota": 4, "comentario": "Peças lindas e únicas! Adorei o atendimento personalizado. Comprei dois vestidos.", "data": "5 dias atrás", "sentimento": "positivo"},
        {"usuario": "Marta V.", "emoji": "👩‍🦳", "nota": 3, "comentario": "Roupas bonitas mas o tamanho P estava bem limitado. Precisam ampliar o estoque.", "data": "2 semanas atrás", "sentimento": "neutro"},
    ],
    6: [
        {"usuario": "Dr. Henrique", "emoji": "👨‍⚕️", "nota": 5, "comentario": "Clínica excelente! Consulta pontual, médicos competentes e infraestrutura muito boa.", "data": "2 dias atrás", "sentimento": "positivo"},
        {"usuario": "Silvia R.", "emoji": "👩", "nota": 4, "comentario": "Agendamento online facilitou muito. Atendimento humanizado e profissionais qualificados.", "data": "1 semana atrás", "sentimento": "positivo"},
        {"usuario": "Antônio B.", "emoji": "👴", "nota": 5, "comentario": "Fisioterapia de alto nível! Me recuperei muito mais rápido do que esperava.", "data": "2 semanas atrás", "sentimento": "positivo"},
    ],
    7: [
        {"usuario": "Felipe C.", "emoji": "👨", "nota": 5, "comentario": "A melhor pizza do Centro sem dúvida. Massa fininha, recheio generoso e delivery rapidíssimo!", "data": "1 dia atrás", "sentimento": "positivo"},
        {"usuario": "Renata O.", "emoji": "👩‍🦰", "nota": 4, "comentario": "Pizza deliciosa! Pedimos a mussarela e a calabresa e as duas estavam ótimas.", "data": "4 dias atrás", "sentimento": "positivo"},
        {"usuario": "Diego M.", "emoji": "🧑", "nota": 3, "comentario": "Sabor bom mas minha pizza chegou morna. Precisam melhorar a embalagem para delivery.", "data": "1 semana atrás", "sentimento": "neutro"},
    ],
    8: [
        {"usuario": "Isabela F.", "emoji": "👩‍🎓", "nota": 5, "comentario": "O açaí mais gostoso de Aracaju! Direto na Praça Olímpio Campos, que lugar mais especial!", "data": "1 dia atrás", "sentimento": "positivo"},
        {"usuario": "Lucas G.", "emoji": "🧑‍🎓", "nota": 5, "comentario": "Porção gigante, açaí cremoso e coberturas deliciosas. O preço é justo para a qualidade.", "data": "2 dias atrás", "sentimento": "positivo"},
        {"usuario": "Vanessa T.", "emoji": "👩", "nota": 5, "comentario": "Venho aqui toda semana! O açaí com tapioca é uma combinação perfeita. Atendimento sempre simpático.", "data": "5 dias atrás", "sentimento": "positivo"},
        {"usuario": "Roberto A.", "emoji": "👨‍🦱", "nota": 4, "comentario": "Muito bom! Na hora do rush a fila anda devagar mas vale cada minuto de espera.", "data": "1 semana atrás", "sentimento": "positivo"},
    ],
    9: [
        {"usuario": "Célia N.", "emoji": "👩‍🦳", "nota": 4, "comentario": "Preços muito bons e fácil de encontrar no Centro. Atendimento rápido.", "data": "3 dias atrás", "sentimento": "positivo"},
        {"usuario": "Manoel S.", "emoji": "👴", "nota": 3, "comentario": "Razoável. Preço bom mas às vezes não têm o remédio que procuro.", "data": "2 semanas atrás", "sentimento": "neutro"},
    ],
    10: [
        {"usuario": "Dona Tereza", "emoji": "👵", "nota": 5, "comentario": "A carne de sol é de comer de joelhos! Comida sergipana de verdade, igualzinho ao que minha mãe fazia.", "data": "1 dia atrás", "sentimento": "positivo"},
        {"usuario": "Wellington C.", "emoji": "👨‍💼", "nota": 5, "comentario": "Almoço perfeito para o dia a dia. Porção generosa, preço justo e tudo muito temperado.", "data": "3 dias atrás", "sentimento": "positivo"},
        {"usuario": "Rafaela B.", "emoji": "👩‍💼", "nota": 4, "comentario": "Comida ótima! O único ponto é que fica muito cheio na hora do almoço.", "data": "1 semana atrás", "sentimento": "positivo"},
    ],
    11: [
        {"usuario": "Beatriz L.", "emoji": "👩‍🦱", "nota": 5, "comentario": "Encontrei meu óculos de grau favorito aqui! Atendimento impecável e preço ótimo.", "data": "1 semana atrás", "sentimento": "positivo"},
        {"usuario": "Cláudio F.", "emoji": "👨‍🦳", "nota": 4, "comentario": "Boa variedade de marcas e o optometrista é muito competente.", "data": "2 semanas atrás", "sentimento": "positivo"},
    ],
    12: [
        {"usuario": "Seu Zé", "emoji": "👴", "nota": 4, "comentario": "Mercadinho simples mas com tudo que preciso. Legumes sempre frescos!", "data": "4 dias atrás", "sentimento": "positivo"},
        {"usuario": "Neide A.", "emoji": "👩‍🦳", "nota": 3, "comentario": "Produtos bons mas o espaço é pequeno e fica apertado.", "data": "2 semanas atrás", "sentimento": "neutro"},
    ],
}

# ── CUPONS EXEMPLO ────────────────────────────────────────────────────────────
CUPONS_EXEMPLO = [
    {"codigo": "ACJ-XING10", "desconto_pct": 15, "comercio": "Churrascaria Xingó", "valido": True},
    {"codigo": "ACJ-CAFE08", "desconto_pct": 10, "comercio": "Café Cotinguiba", "valido": True},
    {"codigo": "ACJ-ACAI03", "desconto_pct": 15, "comercio": "Açaí da Praça", "valido": False},
]

# ── INSIGHTS POR COMÉRCIO (simulados) ─────────────────────────────────────────
INSIGHTS = {
    1: [
        {"tipo": "alerta",        "titulo": "Tempo de espera elevado nos fins de semana", "descricao": "3 avaliações recentes citaram espera acima de 30 min. Considere reforçar a equipe aos sábados.", "prioridade": "alta"},
        {"tipo": "elogio",        "titulo": "Qualidade da carne muito elogiada",          "descricao": "92% das avaliações positivas citam a qualidade da carne como principal destaque.",               "prioridade": "baixa"},
        {"tipo": "recomendacao",  "titulo": "Incentive avaliações no almoço de semana",   "descricao": "Seu movimento de almoço tem poucas avaliações. Ofereça cupom extra para quem avaliar no almoço.", "prioridade": "media"},
    ],
    4: [
        {"tipo": "elogio",        "titulo": "Ambiente muito elogiado",                    "descricao": "Clientes destacam o ambiente aconchegante como principal motivo de retorno.",                       "prioridade": "baixa"},
        {"tipo": "recomendacao",  "titulo": "Explore o público home office",               "descricao": "Vários clientes mencionam usar o café para trabalhar. Considere pacotes de recarga Wi-Fi.",        "prioridade": "media"},
    ],
    8: [
        {"tipo": "elogio",        "titulo": "Localização na praça é um diferencial",      "descricao": "Clientes elogiam a localização na Praça Olímpio Campos. Use isso na sua comunicação.",            "prioridade": "baixa"},
        {"tipo": "alerta",        "titulo": "Fila longa em horários de pico",              "descricao": "Clientes reclamam de fila no fim de tarde. Considere atendente extra das 17h às 19h.",            "prioridade": "alta"},
    ],
}

# ── PERFIS DE CLIENTES (para o painel premium) ────────────────────────────────
PERFIS_CLIENTES = {
    "Churrascaria Xingó":    [("🍽️ Foodies", 38), ("👨‍👩‍👧 Famílias", 30), ("👔 Executivos", 18), ("💑 Casais", 14)],
    "Café Cotinguiba":       [("💻 Home Office", 42), ("💑 Casais", 28), ("🍽️ Foodies", 20), ("🎓 Estudantes", 10)],
    "Açaí da Praça":         [("🎓 Estudantes", 45), ("👨‍👩‍👧 Famílias", 30), ("🏃 Esportistas", 25)],
    "Clínica São Lucas":     [("👴 Idosos", 40), ("👨‍👩‍👧 Famílias", 35), ("👔 Executivos", 25)],
    "Farmácia Saúde Viva":   [("👴 Idosos", 50), ("👨‍👩‍👧 Famílias", 30), ("🏃 Esportistas", 20)],
    "Restaurante Caju & Cia":[("👔 Executivos", 48), ("👨‍👩‍👧 Famílias", 32), ("🍽️ Foodies", 20)],
}

CATEGORIAS = sorted(list(set(c["categoria"] for c in COMERCIOS)))
